### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by kuroyanagi33** [alterzero/DBPN-Pytorch#5]
The environment is pytorch 0.3.1, torchvision 0.2.0, cuda 9.0, cudnn 7, Tesla K80. I think that there is no problem with the image size and batch size being handled, but it causes a memory error. How can I solve it?

```
(miniconda3-latest) kuroyanagi@p-b-s-r001:~/DBPN-Pytorch$ python main.py
Namespace(batchSize=1, data_augmentation=True, data_dir='./Input', gpu_mode=True, gpus=1, hr_test_dataset='VOC2012_valid_HR', hr_train_dataset='VOC2012_train_HR', lr=0.0001, model_type='DBPN', nEpochs=2000, patch_size=32, prefix='dbpn', pretrained=False, pretrained_sr=None, save_folder='weights/', seed=123, snapshots=100, testBatchSize=5, test_dataset='VOC2012_valid_LR_x2', threads=1, train_dataset='VOC2012_train_LR_x2', upscale_factor=2)
===> Loading datasets
===> Building model  DBPN
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    model = torch.nn.DataParallel(model, device_ids=gpus_list)
  File "/home/kuroyanagi@gees.local/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 64, in __init__
    self.module.cuda(device_ids[0])
  File "/home/kuroyanagi@gees.local/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/kuroyanagi@gees.local/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/kuroyanagi@gees.local/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/kuroyanagi@gees.local/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/kuroyanagi@gees.local/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/home/kuroyanagi@gees.local/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/kuroyanagi@gees.local/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu:58
(miniconda3-latest) kuroyanagi@p-b-s-r001:~/DBPN-Pytorch$
```

**Comment by kuroyanagi33** [comment]
I'm sorry. After rebooting it worked fine.

**Comment by jotoy** [comment]
I met the same problem.  After rebooting it didn't work fine.
